name: Valde-Guvenlik-Check

on: [push]

jobs:
  taramalar:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu GitHub'dan Cek
        uses: actions/checkout@v4

      # 1. ADIM: KOD TARAMASI (SAST)
      - name: Bandit ile Python Kod Analizi
        run: |
          pip install bandit
          # -r: klasörü tara, -ll: sadece orta ve yuksek riskleri goster
          bandit -r . -ll 

      # 2. ADIM: DOCKER IMAJINI OLUSTUR
      - name: Docker Imajini Olustur
        run: docker build -t valde-simulasyon:latest .

      # 3. ADIM: DOCKER GUVENLIK TARAMASI (SCA)
      - name: Trivy ile Imaj Analizi (Zafiyet Taramasi)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'valde-simulasyon:latest'
          format: 'table'
          # SADECE ÇÖZÜMÜ OLAN HATALARDA DUR (Yeni sihrimiz bu!)
          ignore-unfixed: true 
          exit-code: '1'
          severity: 'CRITICAL,HIGH'